Move _GNU_SOURCE hint for clone() before header includes
_GNU_SOURCE needs to be defined before unistd.h and sched.h are inclued.
Otherwise gcc can't find clone() and  will throw the following error:

v_asmlnk.c:10590:8: error: implicit declaration of function ‘clone’;
did you mean ‘close’? [-Wimplicit-function-declaration] pid = clone(popen_child_process_func, stack_aligned, ...

Signed-off-by: Jonas K. <j0nask@proton.me>