Add missing external declaration of __add_dmpv_chglst_el_sel
Fixes the following error, I got while compilation:

cvmacros.h:400:5: error: implicit declaration of function ‘__add_dmpv_chglst_el_sel’;
did you mean ‘__add_dp_chglst_el’? [-Wimplicit-function-declaration] __add_dmpv_chglst_el_sel(np, i1);

Signed-off-by: Jonas K. <j0nask@proton.me>